### PR TITLE
Add keyboard shortcuts (#84)

### PR DESCRIPTION
**Pull request by m-Schlitzer**
This commit adds shortcuts for the following commands:
 * uploadScript (ctrl+alt+u)
 * runScript (ctrl+alt+r)
 * uploadRunScript (ctrl+alt+x)
 * uploadJSFromTS (ctrl+alt+j)

### CODE REVIEW

**Comment by bkircher** [comment]
@tineheller Could you review this and take a look if this is Okay with you?

**Comment by bkircher** [comment]
@m-Schlitzer Could you please update the description of this PR to include the issue # you are working on. Even better: If your commit has the line

```
Fixes #84
```

the issue state is automatically updated on merge/push _and_ the description automatically contains a link.

And question: Have you discussed the shortcuts with the users from the original issue? Are they fine with this?

**Comment by tineheller** [comment]
Looks good to me

**Comment by m-Schlitzer** [comment]
My commit references the issue in the title, which automatically updated the issue. The fixes #84 line I'll add next time.

**Comment by bkircher** [comment]
@m-Schlitzer Thanks!

> And question: Have you discussed the shortcuts with the users from the original issue? Are they fine with this?

And this one?

**Comment by m-Schlitzer** [comment]
Oh right, I talked to https://github.com/mpdrescher and he was fine with it, I haven't talked to @FabianTe yet.

**Comment by bkircher** [comment]
Thanks. Done.

**Pull request merged**
