### PR TITLE
remove comment from launch.json

### PR DESCRIPTION
**Pull request by tineheller**
JSON.parse didn't work with comment...

### CODE REVIEW

**Comment by bkircher** [comment]
Why don't we just strip comments from file content before parsing to JSON?

This is JS land, everything is a library \o/
```bash
npm install --save strip-json-comments
npm install --save @types/strip-json-comments
```

and then something along the line of
```typescript
let config = JSON.parse(stripJsonComments(fileContent));
```

**Comment by tineheller** [comment]
as you wish...

**Comment by tineheller** [comment]
why that?:
`npm install --save @types/strip-json-comments`

**Comment by bkircher** [comment]
> why that?:
npm install --save @types/strip-json-comments

To install type definitions for that JS module.

**Pull request closed without merging**
